// Code generated by ent, DO NOT EDIT.

package internal

const IncrementStarts = "{\"bid_account_ca_rel\":34359738368,\"bid_apply\":0,\"bid_ca_certificate\":21474836480,\"bid_expense\":4294967296,\"bid_info\":8589934592,\"bid_member_account\":25769803776,\"bid_project\":12884901888,\"bid_web_site\":30064771072,\"sys_task_log\":17179869184}"
