// Code generated by ent, DO NOT EDIT.

package tasklog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tasklog type in the database.
	Label = "task_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBizType holds the string denoting the biz_type field in the database.
	FieldBizType = "biz_type"
	// FieldBizID holds the string denoting the biz_id field in the database.
	FieldBizID = "biz_id"
	// FieldAssignSeq holds the string denoting the assign_seq field in the database.
	FieldAssignSeq = "assign_seq"
	// FieldAssignTime holds the string denoting the assign_time field in the database.
	FieldAssignTime = "assign_time"
	// FieldHandlerNo holds the string denoting the handler_no field in the database.
	FieldHandlerNo = "handler_no"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// Table holds the table name of the tasklog in the database.
	Table = "sys_task_log"
)

// Columns holds all SQL columns for tasklog fields.
var Columns = []string{
	FieldID,
	FieldBizType,
	FieldBizID,
	FieldAssignSeq,
	FieldAssignTime,
	FieldHandlerNo,
	FieldStartTime,
	FieldEndTime,
	FieldRemark,
	FieldCreatedAt,
	FieldCreatedBy,
	FieldUpdatedAt,
	FieldUpdatedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BizIDValidator is a validator for the "biz_id" field. It is called by the builders before save.
	BizIDValidator func(string) error
	// HandlerNoValidator is a validator for the "handler_no" field. It is called by the builders before save.
	HandlerNoValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	UpdatedByValidator func(string) error
)

// BizType defines the type for the "biz_type" enum field.
type BizType string

// BizType0 is the default value of the BizType enum.
const DefaultBizType = BizType0

// BizType values.
const (
	BizType1 BizType = "1"
	BizType2 BizType = "2"
	BizType0 BizType = "0"
)

func (bt BizType) String() string {
	return string(bt)
}

// BizTypeValidator is a validator for the "biz_type" field enum values. It is called by the builders before save.
func BizTypeValidator(bt BizType) error {
	switch bt {
	case BizType1, BizType2, BizType0:
		return nil
	default:
		return fmt.Errorf("tasklog: invalid enum value for biz_type field: %q", bt)
	}
}

// OrderOption defines the ordering options for the TaskLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBizType orders the results by the biz_type field.
func ByBizType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBizType, opts...).ToFunc()
}

// ByBizID orders the results by the biz_id field.
func ByBizID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBizID, opts...).ToFunc()
}

// ByAssignSeq orders the results by the assign_seq field.
func ByAssignSeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignSeq, opts...).ToFunc()
}

// ByAssignTime orders the results by the assign_time field.
func ByAssignTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignTime, opts...).ToFunc()
}

// ByHandlerNo orders the results by the handler_no field.
func ByHandlerNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandlerNo, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}
