// Code generated by ent, DO NOT EDIT.

package tasklog

import (
	"cds/bid/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldID, id))
}

// BizID applies equality check predicate on the "biz_id" field. It's identical to BizIDEQ.
func BizID(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldBizID, v))
}

// AssignSeq applies equality check predicate on the "assign_seq" field. It's identical to AssignSeqEQ.
func AssignSeq(v uint32) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldAssignSeq, v))
}

// AssignTime applies equality check predicate on the "assign_time" field. It's identical to AssignTimeEQ.
func AssignTime(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldAssignTime, v))
}

// HandlerNo applies equality check predicate on the "handler_no" field. It's identical to HandlerNoEQ.
func HandlerNo(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldHandlerNo, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldEndTime, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldRemark, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldUpdatedBy, v))
}

// BizTypeEQ applies the EQ predicate on the "biz_type" field.
func BizTypeEQ(v BizType) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldBizType, v))
}

// BizTypeNEQ applies the NEQ predicate on the "biz_type" field.
func BizTypeNEQ(v BizType) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldBizType, v))
}

// BizTypeIn applies the In predicate on the "biz_type" field.
func BizTypeIn(vs ...BizType) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldBizType, vs...))
}

// BizTypeNotIn applies the NotIn predicate on the "biz_type" field.
func BizTypeNotIn(vs ...BizType) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldBizType, vs...))
}

// BizIDEQ applies the EQ predicate on the "biz_id" field.
func BizIDEQ(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldBizID, v))
}

// BizIDNEQ applies the NEQ predicate on the "biz_id" field.
func BizIDNEQ(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldBizID, v))
}

// BizIDIn applies the In predicate on the "biz_id" field.
func BizIDIn(vs ...string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldBizID, vs...))
}

// BizIDNotIn applies the NotIn predicate on the "biz_id" field.
func BizIDNotIn(vs ...string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldBizID, vs...))
}

// BizIDGT applies the GT predicate on the "biz_id" field.
func BizIDGT(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldBizID, v))
}

// BizIDGTE applies the GTE predicate on the "biz_id" field.
func BizIDGTE(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldBizID, v))
}

// BizIDLT applies the LT predicate on the "biz_id" field.
func BizIDLT(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldBizID, v))
}

// BizIDLTE applies the LTE predicate on the "biz_id" field.
func BizIDLTE(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldBizID, v))
}

// BizIDContains applies the Contains predicate on the "biz_id" field.
func BizIDContains(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldContains(FieldBizID, v))
}

// BizIDHasPrefix applies the HasPrefix predicate on the "biz_id" field.
func BizIDHasPrefix(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldHasPrefix(FieldBizID, v))
}

// BizIDHasSuffix applies the HasSuffix predicate on the "biz_id" field.
func BizIDHasSuffix(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldHasSuffix(FieldBizID, v))
}

// BizIDEqualFold applies the EqualFold predicate on the "biz_id" field.
func BizIDEqualFold(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEqualFold(FieldBizID, v))
}

// BizIDContainsFold applies the ContainsFold predicate on the "biz_id" field.
func BizIDContainsFold(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldContainsFold(FieldBizID, v))
}

// AssignSeqEQ applies the EQ predicate on the "assign_seq" field.
func AssignSeqEQ(v uint32) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldAssignSeq, v))
}

// AssignSeqNEQ applies the NEQ predicate on the "assign_seq" field.
func AssignSeqNEQ(v uint32) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldAssignSeq, v))
}

// AssignSeqIn applies the In predicate on the "assign_seq" field.
func AssignSeqIn(vs ...uint32) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldAssignSeq, vs...))
}

// AssignSeqNotIn applies the NotIn predicate on the "assign_seq" field.
func AssignSeqNotIn(vs ...uint32) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldAssignSeq, vs...))
}

// AssignSeqGT applies the GT predicate on the "assign_seq" field.
func AssignSeqGT(v uint32) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldAssignSeq, v))
}

// AssignSeqGTE applies the GTE predicate on the "assign_seq" field.
func AssignSeqGTE(v uint32) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldAssignSeq, v))
}

// AssignSeqLT applies the LT predicate on the "assign_seq" field.
func AssignSeqLT(v uint32) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldAssignSeq, v))
}

// AssignSeqLTE applies the LTE predicate on the "assign_seq" field.
func AssignSeqLTE(v uint32) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldAssignSeq, v))
}

// AssignTimeEQ applies the EQ predicate on the "assign_time" field.
func AssignTimeEQ(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldAssignTime, v))
}

// AssignTimeNEQ applies the NEQ predicate on the "assign_time" field.
func AssignTimeNEQ(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldAssignTime, v))
}

// AssignTimeIn applies the In predicate on the "assign_time" field.
func AssignTimeIn(vs ...time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldAssignTime, vs...))
}

// AssignTimeNotIn applies the NotIn predicate on the "assign_time" field.
func AssignTimeNotIn(vs ...time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldAssignTime, vs...))
}

// AssignTimeGT applies the GT predicate on the "assign_time" field.
func AssignTimeGT(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldAssignTime, v))
}

// AssignTimeGTE applies the GTE predicate on the "assign_time" field.
func AssignTimeGTE(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldAssignTime, v))
}

// AssignTimeLT applies the LT predicate on the "assign_time" field.
func AssignTimeLT(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldAssignTime, v))
}

// AssignTimeLTE applies the LTE predicate on the "assign_time" field.
func AssignTimeLTE(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldAssignTime, v))
}

// AssignTimeIsNil applies the IsNil predicate on the "assign_time" field.
func AssignTimeIsNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIsNull(FieldAssignTime))
}

// AssignTimeNotNil applies the NotNil predicate on the "assign_time" field.
func AssignTimeNotNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotNull(FieldAssignTime))
}

// HandlerNoEQ applies the EQ predicate on the "handler_no" field.
func HandlerNoEQ(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldHandlerNo, v))
}

// HandlerNoNEQ applies the NEQ predicate on the "handler_no" field.
func HandlerNoNEQ(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldHandlerNo, v))
}

// HandlerNoIn applies the In predicate on the "handler_no" field.
func HandlerNoIn(vs ...string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldHandlerNo, vs...))
}

// HandlerNoNotIn applies the NotIn predicate on the "handler_no" field.
func HandlerNoNotIn(vs ...string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldHandlerNo, vs...))
}

// HandlerNoGT applies the GT predicate on the "handler_no" field.
func HandlerNoGT(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldHandlerNo, v))
}

// HandlerNoGTE applies the GTE predicate on the "handler_no" field.
func HandlerNoGTE(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldHandlerNo, v))
}

// HandlerNoLT applies the LT predicate on the "handler_no" field.
func HandlerNoLT(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldHandlerNo, v))
}

// HandlerNoLTE applies the LTE predicate on the "handler_no" field.
func HandlerNoLTE(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldHandlerNo, v))
}

// HandlerNoContains applies the Contains predicate on the "handler_no" field.
func HandlerNoContains(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldContains(FieldHandlerNo, v))
}

// HandlerNoHasPrefix applies the HasPrefix predicate on the "handler_no" field.
func HandlerNoHasPrefix(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldHasPrefix(FieldHandlerNo, v))
}

// HandlerNoHasSuffix applies the HasSuffix predicate on the "handler_no" field.
func HandlerNoHasSuffix(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldHasSuffix(FieldHandlerNo, v))
}

// HandlerNoIsNil applies the IsNil predicate on the "handler_no" field.
func HandlerNoIsNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIsNull(FieldHandlerNo))
}

// HandlerNoNotNil applies the NotNil predicate on the "handler_no" field.
func HandlerNoNotNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotNull(FieldHandlerNo))
}

// HandlerNoEqualFold applies the EqualFold predicate on the "handler_no" field.
func HandlerNoEqualFold(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEqualFold(FieldHandlerNo, v))
}

// HandlerNoContainsFold applies the ContainsFold predicate on the "handler_no" field.
func HandlerNoContainsFold(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldContainsFold(FieldHandlerNo, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldStartTime, v))
}

// StartTimeIsNil applies the IsNil predicate on the "start_time" field.
func StartTimeIsNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIsNull(FieldStartTime))
}

// StartTimeNotNil applies the NotNil predicate on the "start_time" field.
func StartTimeNotNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotNull(FieldStartTime))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldEndTime, v))
}

// EndTimeIsNil applies the IsNil predicate on the "end_time" field.
func EndTimeIsNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIsNull(FieldEndTime))
}

// EndTimeNotNil applies the NotNil predicate on the "end_time" field.
func EndTimeNotNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotNull(FieldEndTime))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldContainsFold(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.TaskLog {
	return predicate.TaskLog(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.TaskLog {
	return predicate.TaskLog(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskLog) predicate.TaskLog {
	return predicate.TaskLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskLog) predicate.TaskLog {
	return predicate.TaskLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskLog) predicate.TaskLog {
	return predicate.TaskLog(sql.NotPredicates(p))
}
