// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cds/bid/ent/bidaccountrelation"
	"cds/bid/ent/bidcacertificate"
	"cds/bid/ent/bidmemberaccount"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 账号证书关联关系
type BidAccountRelation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 会员账号ID
	AccountID string `json:"account_id,omitempty"`
	// CA证书ID
	CaID string `json:"ca_id,omitempty"`
	// 关联备注
	Remark string `json:"remark,omitempty"`
	// BindAt holds the value of the "bind_at" field.
	BindAt time.Time `json:"bind_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BidAccountRelationQuery when eager-loading is set.
	Edges        BidAccountRelationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BidAccountRelationEdges holds the relations/edges for other nodes in the graph.
type BidAccountRelationEdges struct {
	// Account holds the value of the account edge.
	Account *BidMemberAccount `json:"account,omitempty"`
	// CaCertificate holds the value of the ca_certificate edge.
	CaCertificate *BidCACertificate `json:"ca_certificate,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BidAccountRelationEdges) AccountOrErr() (*BidMemberAccount, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: bidmemberaccount.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// CaCertificateOrErr returns the CaCertificate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BidAccountRelationEdges) CaCertificateOrErr() (*BidCACertificate, error) {
	if e.CaCertificate != nil {
		return e.CaCertificate, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: bidcacertificate.Label}
	}
	return nil, &NotLoadedError{edge: "ca_certificate"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BidAccountRelation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bidaccountrelation.FieldID:
			values[i] = new(sql.NullInt64)
		case bidaccountrelation.FieldAccountID, bidaccountrelation.FieldCaID, bidaccountrelation.FieldRemark:
			values[i] = new(sql.NullString)
		case bidaccountrelation.FieldBindAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BidAccountRelation fields.
func (_m *BidAccountRelation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bidaccountrelation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case bidaccountrelation.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case bidaccountrelation.FieldCaID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ca_id", values[i])
			} else if value.Valid {
				_m.CaID = value.String
			}
		case bidaccountrelation.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		case bidaccountrelation.FieldBindAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bind_at", values[i])
			} else if value.Valid {
				_m.BindAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BidAccountRelation.
// This includes values selected through modifiers, order, etc.
func (_m *BidAccountRelation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the BidAccountRelation entity.
func (_m *BidAccountRelation) QueryAccount() *BidMemberAccountQuery {
	return NewBidAccountRelationClient(_m.config).QueryAccount(_m)
}

// QueryCaCertificate queries the "ca_certificate" edge of the BidAccountRelation entity.
func (_m *BidAccountRelation) QueryCaCertificate() *BidCACertificateQuery {
	return NewBidAccountRelationClient(_m.config).QueryCaCertificate(_m)
}

// Update returns a builder for updating this BidAccountRelation.
// Note that you need to call BidAccountRelation.Unwrap() before calling this method if this BidAccountRelation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BidAccountRelation) Update() *BidAccountRelationUpdateOne {
	return NewBidAccountRelationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BidAccountRelation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BidAccountRelation) Unwrap() *BidAccountRelation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BidAccountRelation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BidAccountRelation) String() string {
	var builder strings.Builder
	builder.WriteString("BidAccountRelation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("ca_id=")
	builder.WriteString(_m.CaID)
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteString(", ")
	builder.WriteString("bind_at=")
	builder.WriteString(_m.BindAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BidAccountRelations is a parsable slice of BidAccountRelation.
type BidAccountRelations []*BidAccountRelation
