// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cds/bid/ent/bidinfo"
	"cds/bid/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BidInfoDelete is the builder for deleting a BidInfo entity.
type BidInfoDelete struct {
	config
	hooks    []Hook
	mutation *BidInfoMutation
}

// Where appends a list predicates to the BidInfoDelete builder.
func (_d *BidInfoDelete) Where(ps ...predicate.BidInfo) *BidInfoDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BidInfoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BidInfoDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BidInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bidinfo.Table, sqlgraph.NewFieldSpec(bidinfo.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BidInfoDeleteOne is the builder for deleting a single BidInfo entity.
type BidInfoDeleteOne struct {
	_d *BidInfoDelete
}

// Where appends a list predicates to the BidInfoDelete builder.
func (_d *BidInfoDeleteOne) Where(ps ...predicate.BidInfo) *BidInfoDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BidInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bidinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BidInfoDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
