// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cds/bid/ent/bidapply"
	"cds/bid/ent/bidexpense"
	"cds/bid/ent/bidinfo"
	"cds/bid/ent/bidproject"
	"cds/bid/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BidProjectQuery is the builder for querying BidProject entities.
type BidProjectQuery struct {
	config
	ctx         *QueryContext
	order       []bidproject.OrderOption
	inters      []Interceptor
	predicates  []predicate.BidProject
	withApply   *BidApplyQuery
	withExpense *BidExpenseQuery
	withInfo    *BidInfoQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BidProjectQuery builder.
func (_q *BidProjectQuery) Where(ps ...predicate.BidProject) *BidProjectQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BidProjectQuery) Limit(limit int) *BidProjectQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BidProjectQuery) Offset(offset int) *BidProjectQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BidProjectQuery) Unique(unique bool) *BidProjectQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BidProjectQuery) Order(o ...bidproject.OrderOption) *BidProjectQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryApply chains the current query on the "apply" edge.
func (_q *BidProjectQuery) QueryApply() *BidApplyQuery {
	query := (&BidApplyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bidproject.Table, bidproject.FieldID, selector),
			sqlgraph.To(bidapply.Table, bidapply.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, bidproject.ApplyTable, bidproject.ApplyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExpense chains the current query on the "expense" edge.
func (_q *BidProjectQuery) QueryExpense() *BidExpenseQuery {
	query := (&BidExpenseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bidproject.Table, bidproject.FieldID, selector),
			sqlgraph.To(bidexpense.Table, bidexpense.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bidproject.ExpenseTable, bidproject.ExpenseColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInfo chains the current query on the "info" edge.
func (_q *BidProjectQuery) QueryInfo() *BidInfoQuery {
	query := (&BidInfoClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bidproject.Table, bidproject.FieldID, selector),
			sqlgraph.To(bidinfo.Table, bidinfo.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, bidproject.InfoTable, bidproject.InfoColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BidProject entity from the query.
// Returns a *NotFoundError when no BidProject was found.
func (_q *BidProjectQuery) First(ctx context.Context) (*BidProject, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bidproject.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BidProjectQuery) FirstX(ctx context.Context) *BidProject {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BidProject ID from the query.
// Returns a *NotFoundError when no BidProject ID was found.
func (_q *BidProjectQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bidproject.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BidProjectQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BidProject entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BidProject entity is found.
// Returns a *NotFoundError when no BidProject entities are found.
func (_q *BidProjectQuery) Only(ctx context.Context) (*BidProject, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bidproject.Label}
	default:
		return nil, &NotSingularError{bidproject.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BidProjectQuery) OnlyX(ctx context.Context) *BidProject {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BidProject ID in the query.
// Returns a *NotSingularError when more than one BidProject ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BidProjectQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bidproject.Label}
	default:
		err = &NotSingularError{bidproject.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BidProjectQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BidProjects.
func (_q *BidProjectQuery) All(ctx context.Context) ([]*BidProject, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BidProject, *BidProjectQuery]()
	return withInterceptors[[]*BidProject](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BidProjectQuery) AllX(ctx context.Context) []*BidProject {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BidProject IDs.
func (_q *BidProjectQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(bidproject.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BidProjectQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BidProjectQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BidProjectQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BidProjectQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BidProjectQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BidProjectQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BidProjectQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BidProjectQuery) Clone() *BidProjectQuery {
	if _q == nil {
		return nil
	}
	return &BidProjectQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]bidproject.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.BidProject{}, _q.predicates...),
		withApply:   _q.withApply.Clone(),
		withExpense: _q.withExpense.Clone(),
		withInfo:    _q.withInfo.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithApply tells the query-builder to eager-load the nodes that are connected to
// the "apply" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BidProjectQuery) WithApply(opts ...func(*BidApplyQuery)) *BidProjectQuery {
	query := (&BidApplyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withApply = query
	return _q
}

// WithExpense tells the query-builder to eager-load the nodes that are connected to
// the "expense" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BidProjectQuery) WithExpense(opts ...func(*BidExpenseQuery)) *BidProjectQuery {
	query := (&BidExpenseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withExpense = query
	return _q
}

// WithInfo tells the query-builder to eager-load the nodes that are connected to
// the "info" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BidProjectQuery) WithInfo(opts ...func(*BidInfoQuery)) *BidProjectQuery {
	query := (&BidInfoClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInfo = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BidProject.Query().
//		GroupBy(bidproject.FieldCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BidProjectQuery) GroupBy(field string, fields ...string) *BidProjectGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BidProjectGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = bidproject.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//	}
//
//	client.BidProject.Query().
//		Select(bidproject.FieldCode).
//		Scan(ctx, &v)
func (_q *BidProjectQuery) Select(fields ...string) *BidProjectSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BidProjectSelect{BidProjectQuery: _q}
	sbuild.label = bidproject.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BidProjectSelect configured with the given aggregations.
func (_q *BidProjectQuery) Aggregate(fns ...AggregateFunc) *BidProjectSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BidProjectQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !bidproject.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BidProjectQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BidProject, error) {
	var (
		nodes       = []*BidProject{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withApply != nil,
			_q.withExpense != nil,
			_q.withInfo != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BidProject).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BidProject{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withApply; query != nil {
		if err := _q.loadApply(ctx, query, nodes, nil,
			func(n *BidProject, e *BidApply) { n.Edges.Apply = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withExpense; query != nil {
		if err := _q.loadExpense(ctx, query, nodes,
			func(n *BidProject) { n.Edges.Expense = []*BidExpense{} },
			func(n *BidProject, e *BidExpense) { n.Edges.Expense = append(n.Edges.Expense, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withInfo; query != nil {
		if err := _q.loadInfo(ctx, query, nodes, nil,
			func(n *BidProject, e *BidInfo) { n.Edges.Info = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BidProjectQuery) loadApply(ctx context.Context, query *BidApplyQuery, nodes []*BidProject, init func(*BidProject), assign func(*BidProject, *BidApply)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*BidProject)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(bidapply.FieldProjectID)
	}
	query.Where(predicate.BidApply(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(bidproject.ApplyColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProjectID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "project_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *BidProjectQuery) loadExpense(ctx context.Context, query *BidExpenseQuery, nodes []*BidProject, init func(*BidProject), assign func(*BidProject, *BidExpense)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*BidProject)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(bidexpense.FieldProjectID)
	}
	query.Where(predicate.BidExpense(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(bidproject.ExpenseColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProjectID
		if fk == nil {
			return fmt.Errorf(`foreign-key "project_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "project_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *BidProjectQuery) loadInfo(ctx context.Context, query *BidInfoQuery, nodes []*BidProject, init func(*BidProject), assign func(*BidProject, *BidInfo)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*BidProject)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(bidinfo.FieldProjectID)
	}
	query.Where(predicate.BidInfo(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(bidproject.InfoColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProjectID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "project_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *BidProjectQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BidProjectQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bidproject.Table, bidproject.Columns, sqlgraph.NewFieldSpec(bidproject.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bidproject.FieldID)
		for i := range fields {
			if fields[i] != bidproject.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BidProjectQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(bidproject.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = bidproject.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *BidProjectQuery) Modify(modifiers ...func(s *sql.Selector)) *BidProjectSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// BidProjectGroupBy is the group-by builder for BidProject entities.
type BidProjectGroupBy struct {
	selector
	build *BidProjectQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BidProjectGroupBy) Aggregate(fns ...AggregateFunc) *BidProjectGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BidProjectGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BidProjectQuery, *BidProjectGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BidProjectGroupBy) sqlScan(ctx context.Context, root *BidProjectQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BidProjectSelect is the builder for selecting fields of BidProject entities.
type BidProjectSelect struct {
	*BidProjectQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BidProjectSelect) Aggregate(fns ...AggregateFunc) *BidProjectSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BidProjectSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BidProjectQuery, *BidProjectSelect](ctx, _s.BidProjectQuery, _s, _s.inters, v)
}

func (_s *BidProjectSelect) sqlScan(ctx context.Context, root *BidProjectQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *BidProjectSelect) Modify(modifiers ...func(s *sql.Selector)) *BidProjectSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
