// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cds/bid/ent/bidmemberaccount"
	"cds/bid/ent/bidwebsite"
	"cds/bid/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BidWebSiteUpdate is the builder for updating BidWebSite entities.
type BidWebSiteUpdate struct {
	config
	hooks     []Hook
	mutation  *BidWebSiteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BidWebSiteUpdate builder.
func (_u *BidWebSiteUpdate) Where(ps ...predicate.BidWebSite) *BidWebSiteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvince sets the "province" field.
func (_u *BidWebSiteUpdate) SetProvince(v string) *BidWebSiteUpdate {
	_u.mutation.SetProvince(v)
	return _u
}

// SetNillableProvince sets the "province" field if the given value is not nil.
func (_u *BidWebSiteUpdate) SetNillableProvince(v *string) *BidWebSiteUpdate {
	if v != nil {
		_u.SetProvince(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *BidWebSiteUpdate) SetCity(v string) *BidWebSiteUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *BidWebSiteUpdate) SetNillableCity(v *string) *BidWebSiteUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *BidWebSiteUpdate) ClearCity() *BidWebSiteUpdate {
	_u.mutation.ClearCity()
	return _u
}

// SetName sets the "name" field.
func (_u *BidWebSiteUpdate) SetName(v string) *BidWebSiteUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BidWebSiteUpdate) SetNillableName(v *string) *BidWebSiteUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *BidWebSiteUpdate) SetURL(v string) *BidWebSiteUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *BidWebSiteUpdate) SetNillableURL(v *string) *BidWebSiteUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *BidWebSiteUpdate) SetActive(v bool) *BidWebSiteUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *BidWebSiteUpdate) SetNillableActive(v *bool) *BidWebSiteUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *BidWebSiteUpdate) SetRemark(v string) *BidWebSiteUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *BidWebSiteUpdate) SetNillableRemark(v *string) *BidWebSiteUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *BidWebSiteUpdate) ClearRemark() *BidWebSiteUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BidWebSiteUpdate) SetCreatedAt(v time.Time) *BidWebSiteUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BidWebSiteUpdate) SetNillableCreatedAt(v *time.Time) *BidWebSiteUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BidWebSiteUpdate) SetCreatedBy(v string) *BidWebSiteUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BidWebSiteUpdate) SetNillableCreatedBy(v *string) *BidWebSiteUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *BidWebSiteUpdate) ClearCreatedBy() *BidWebSiteUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BidWebSiteUpdate) SetUpdatedAt(v time.Time) *BidWebSiteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BidWebSiteUpdate) SetUpdatedBy(v string) *BidWebSiteUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BidWebSiteUpdate) SetNillableUpdatedBy(v *string) *BidWebSiteUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *BidWebSiteUpdate) ClearUpdatedBy() *BidWebSiteUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// AddMemberAccountIDs adds the "member_accounts" edge to the BidMemberAccount entity by IDs.
func (_u *BidWebSiteUpdate) AddMemberAccountIDs(ids ...string) *BidWebSiteUpdate {
	_u.mutation.AddMemberAccountIDs(ids...)
	return _u
}

// AddMemberAccounts adds the "member_accounts" edges to the BidMemberAccount entity.
func (_u *BidWebSiteUpdate) AddMemberAccounts(v ...*BidMemberAccount) *BidWebSiteUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberAccountIDs(ids...)
}

// Mutation returns the BidWebSiteMutation object of the builder.
func (_u *BidWebSiteUpdate) Mutation() *BidWebSiteMutation {
	return _u.mutation
}

// ClearMemberAccounts clears all "member_accounts" edges to the BidMemberAccount entity.
func (_u *BidWebSiteUpdate) ClearMemberAccounts() *BidWebSiteUpdate {
	_u.mutation.ClearMemberAccounts()
	return _u
}

// RemoveMemberAccountIDs removes the "member_accounts" edge to BidMemberAccount entities by IDs.
func (_u *BidWebSiteUpdate) RemoveMemberAccountIDs(ids ...string) *BidWebSiteUpdate {
	_u.mutation.RemoveMemberAccountIDs(ids...)
	return _u
}

// RemoveMemberAccounts removes "member_accounts" edges to BidMemberAccount entities.
func (_u *BidWebSiteUpdate) RemoveMemberAccounts(v ...*BidMemberAccount) *BidWebSiteUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BidWebSiteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BidWebSiteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BidWebSiteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BidWebSiteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BidWebSiteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bidwebsite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BidWebSiteUpdate) check() error {
	if v, ok := _u.mutation.Province(); ok {
		if err := bidwebsite.ProvinceValidator(v); err != nil {
			return &ValidationError{Name: "province", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.province": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := bidwebsite.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := bidwebsite.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := bidwebsite.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := bidwebsite.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.updated_by": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BidWebSiteUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BidWebSiteUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BidWebSiteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bidwebsite.Table, bidwebsite.Columns, sqlgraph.NewFieldSpec(bidwebsite.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Province(); ok {
		_spec.SetField(bidwebsite.FieldProvince, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(bidwebsite.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(bidwebsite.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bidwebsite.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(bidwebsite.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(bidwebsite.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(bidwebsite.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(bidwebsite.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(bidwebsite.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(bidwebsite.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(bidwebsite.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bidwebsite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(bidwebsite.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(bidwebsite.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.MemberAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bidwebsite.MemberAccountsTable,
			Columns: []string{bidwebsite.MemberAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bidmemberaccount.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberAccountsIDs(); len(nodes) > 0 && !_u.mutation.MemberAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bidwebsite.MemberAccountsTable,
			Columns: []string{bidwebsite.MemberAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bidmemberaccount.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bidwebsite.MemberAccountsTable,
			Columns: []string{bidwebsite.MemberAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bidmemberaccount.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bidwebsite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BidWebSiteUpdateOne is the builder for updating a single BidWebSite entity.
type BidWebSiteUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BidWebSiteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetProvince sets the "province" field.
func (_u *BidWebSiteUpdateOne) SetProvince(v string) *BidWebSiteUpdateOne {
	_u.mutation.SetProvince(v)
	return _u
}

// SetNillableProvince sets the "province" field if the given value is not nil.
func (_u *BidWebSiteUpdateOne) SetNillableProvince(v *string) *BidWebSiteUpdateOne {
	if v != nil {
		_u.SetProvince(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *BidWebSiteUpdateOne) SetCity(v string) *BidWebSiteUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *BidWebSiteUpdateOne) SetNillableCity(v *string) *BidWebSiteUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *BidWebSiteUpdateOne) ClearCity() *BidWebSiteUpdateOne {
	_u.mutation.ClearCity()
	return _u
}

// SetName sets the "name" field.
func (_u *BidWebSiteUpdateOne) SetName(v string) *BidWebSiteUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BidWebSiteUpdateOne) SetNillableName(v *string) *BidWebSiteUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *BidWebSiteUpdateOne) SetURL(v string) *BidWebSiteUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *BidWebSiteUpdateOne) SetNillableURL(v *string) *BidWebSiteUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *BidWebSiteUpdateOne) SetActive(v bool) *BidWebSiteUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *BidWebSiteUpdateOne) SetNillableActive(v *bool) *BidWebSiteUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *BidWebSiteUpdateOne) SetRemark(v string) *BidWebSiteUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *BidWebSiteUpdateOne) SetNillableRemark(v *string) *BidWebSiteUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *BidWebSiteUpdateOne) ClearRemark() *BidWebSiteUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BidWebSiteUpdateOne) SetCreatedAt(v time.Time) *BidWebSiteUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BidWebSiteUpdateOne) SetNillableCreatedAt(v *time.Time) *BidWebSiteUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BidWebSiteUpdateOne) SetCreatedBy(v string) *BidWebSiteUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BidWebSiteUpdateOne) SetNillableCreatedBy(v *string) *BidWebSiteUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *BidWebSiteUpdateOne) ClearCreatedBy() *BidWebSiteUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BidWebSiteUpdateOne) SetUpdatedAt(v time.Time) *BidWebSiteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BidWebSiteUpdateOne) SetUpdatedBy(v string) *BidWebSiteUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BidWebSiteUpdateOne) SetNillableUpdatedBy(v *string) *BidWebSiteUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *BidWebSiteUpdateOne) ClearUpdatedBy() *BidWebSiteUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// AddMemberAccountIDs adds the "member_accounts" edge to the BidMemberAccount entity by IDs.
func (_u *BidWebSiteUpdateOne) AddMemberAccountIDs(ids ...string) *BidWebSiteUpdateOne {
	_u.mutation.AddMemberAccountIDs(ids...)
	return _u
}

// AddMemberAccounts adds the "member_accounts" edges to the BidMemberAccount entity.
func (_u *BidWebSiteUpdateOne) AddMemberAccounts(v ...*BidMemberAccount) *BidWebSiteUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberAccountIDs(ids...)
}

// Mutation returns the BidWebSiteMutation object of the builder.
func (_u *BidWebSiteUpdateOne) Mutation() *BidWebSiteMutation {
	return _u.mutation
}

// ClearMemberAccounts clears all "member_accounts" edges to the BidMemberAccount entity.
func (_u *BidWebSiteUpdateOne) ClearMemberAccounts() *BidWebSiteUpdateOne {
	_u.mutation.ClearMemberAccounts()
	return _u
}

// RemoveMemberAccountIDs removes the "member_accounts" edge to BidMemberAccount entities by IDs.
func (_u *BidWebSiteUpdateOne) RemoveMemberAccountIDs(ids ...string) *BidWebSiteUpdateOne {
	_u.mutation.RemoveMemberAccountIDs(ids...)
	return _u
}

// RemoveMemberAccounts removes "member_accounts" edges to BidMemberAccount entities.
func (_u *BidWebSiteUpdateOne) RemoveMemberAccounts(v ...*BidMemberAccount) *BidWebSiteUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberAccountIDs(ids...)
}

// Where appends a list predicates to the BidWebSiteUpdate builder.
func (_u *BidWebSiteUpdateOne) Where(ps ...predicate.BidWebSite) *BidWebSiteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BidWebSiteUpdateOne) Select(field string, fields ...string) *BidWebSiteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BidWebSite entity.
func (_u *BidWebSiteUpdateOne) Save(ctx context.Context) (*BidWebSite, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BidWebSiteUpdateOne) SaveX(ctx context.Context) *BidWebSite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BidWebSiteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BidWebSiteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BidWebSiteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bidwebsite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BidWebSiteUpdateOne) check() error {
	if v, ok := _u.mutation.Province(); ok {
		if err := bidwebsite.ProvinceValidator(v); err != nil {
			return &ValidationError{Name: "province", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.province": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := bidwebsite.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := bidwebsite.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := bidwebsite.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := bidwebsite.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.updated_by": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BidWebSiteUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BidWebSiteUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BidWebSiteUpdateOne) sqlSave(ctx context.Context) (_node *BidWebSite, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bidwebsite.Table, bidwebsite.Columns, sqlgraph.NewFieldSpec(bidwebsite.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BidWebSite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bidwebsite.FieldID)
		for _, f := range fields {
			if !bidwebsite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bidwebsite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Province(); ok {
		_spec.SetField(bidwebsite.FieldProvince, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(bidwebsite.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(bidwebsite.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bidwebsite.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(bidwebsite.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(bidwebsite.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(bidwebsite.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(bidwebsite.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(bidwebsite.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(bidwebsite.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(bidwebsite.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bidwebsite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(bidwebsite.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(bidwebsite.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.MemberAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bidwebsite.MemberAccountsTable,
			Columns: []string{bidwebsite.MemberAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bidmemberaccount.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberAccountsIDs(); len(nodes) > 0 && !_u.mutation.MemberAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bidwebsite.MemberAccountsTable,
			Columns: []string{bidwebsite.MemberAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bidmemberaccount.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bidwebsite.MemberAccountsTable,
			Columns: []string{bidwebsite.MemberAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bidmemberaccount.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &BidWebSite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bidwebsite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
