// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cds/bid/ent/bidmemberaccount"
	"cds/bid/ent/bidwebsite"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BidWebSiteCreate is the builder for creating a BidWebSite entity.
type BidWebSiteCreate struct {
	config
	mutation *BidWebSiteMutation
	hooks    []Hook
}

// SetProvince sets the "province" field.
func (_c *BidWebSiteCreate) SetProvince(v string) *BidWebSiteCreate {
	_c.mutation.SetProvince(v)
	return _c
}

// SetCity sets the "city" field.
func (_c *BidWebSiteCreate) SetCity(v string) *BidWebSiteCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *BidWebSiteCreate) SetNillableCity(v *string) *BidWebSiteCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *BidWebSiteCreate) SetName(v string) *BidWebSiteCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *BidWebSiteCreate) SetURL(v string) *BidWebSiteCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *BidWebSiteCreate) SetActive(v bool) *BidWebSiteCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *BidWebSiteCreate) SetNillableActive(v *bool) *BidWebSiteCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *BidWebSiteCreate) SetRemark(v string) *BidWebSiteCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *BidWebSiteCreate) SetNillableRemark(v *string) *BidWebSiteCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BidWebSiteCreate) SetCreatedAt(v time.Time) *BidWebSiteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BidWebSiteCreate) SetNillableCreatedAt(v *time.Time) *BidWebSiteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *BidWebSiteCreate) SetCreatedBy(v string) *BidWebSiteCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *BidWebSiteCreate) SetNillableCreatedBy(v *string) *BidWebSiteCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BidWebSiteCreate) SetUpdatedAt(v time.Time) *BidWebSiteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BidWebSiteCreate) SetNillableUpdatedAt(v *time.Time) *BidWebSiteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *BidWebSiteCreate) SetUpdatedBy(v string) *BidWebSiteCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *BidWebSiteCreate) SetNillableUpdatedBy(v *string) *BidWebSiteCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BidWebSiteCreate) SetID(v string) *BidWebSiteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BidWebSiteCreate) SetNillableID(v *string) *BidWebSiteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddMemberAccountIDs adds the "member_accounts" edge to the BidMemberAccount entity by IDs.
func (_c *BidWebSiteCreate) AddMemberAccountIDs(ids ...string) *BidWebSiteCreate {
	_c.mutation.AddMemberAccountIDs(ids...)
	return _c
}

// AddMemberAccounts adds the "member_accounts" edges to the BidMemberAccount entity.
func (_c *BidWebSiteCreate) AddMemberAccounts(v ...*BidMemberAccount) *BidWebSiteCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberAccountIDs(ids...)
}

// Mutation returns the BidWebSiteMutation object of the builder.
func (_c *BidWebSiteCreate) Mutation() *BidWebSiteMutation {
	return _c.mutation
}

// Save creates the BidWebSite in the database.
func (_c *BidWebSiteCreate) Save(ctx context.Context) (*BidWebSite, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BidWebSiteCreate) SaveX(ctx context.Context) *BidWebSite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BidWebSiteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BidWebSiteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BidWebSiteCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := bidwebsite.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := bidwebsite.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := bidwebsite.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := bidwebsite.DefaultID
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BidWebSiteCreate) check() error {
	if _, ok := _c.mutation.Province(); !ok {
		return &ValidationError{Name: "province", err: errors.New(`ent: missing required field "BidWebSite.province"`)}
	}
	if v, ok := _c.mutation.Province(); ok {
		if err := bidwebsite.ProvinceValidator(v); err != nil {
			return &ValidationError{Name: "province", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.province": %w`, err)}
		}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := bidwebsite.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BidWebSite.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := bidwebsite.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "BidWebSite.url"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "BidWebSite.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BidWebSite.created_at"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := bidwebsite.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BidWebSite.updated_at"`)}
	}
	if v, ok := _c.mutation.UpdatedBy(); ok {
		if err := bidwebsite.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.updated_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := bidwebsite.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "BidWebSite.id": %w`, err)}
		}
	}
	return nil
}

func (_c *BidWebSiteCreate) sqlSave(ctx context.Context) (*BidWebSite, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BidWebSite.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BidWebSiteCreate) createSpec() (*BidWebSite, *sqlgraph.CreateSpec) {
	var (
		_node = &BidWebSite{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bidwebsite.Table, sqlgraph.NewFieldSpec(bidwebsite.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Province(); ok {
		_spec.SetField(bidwebsite.FieldProvince, field.TypeString, value)
		_node.Province = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(bidwebsite.FieldCity, field.TypeString, value)
		_node.City = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(bidwebsite.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(bidwebsite.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(bidwebsite.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(bidwebsite.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(bidwebsite.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(bidwebsite.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(bidwebsite.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(bidwebsite.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = &value
	}
	if nodes := _c.mutation.MemberAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bidwebsite.MemberAccountsTable,
			Columns: []string{bidwebsite.MemberAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bidmemberaccount.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BidWebSiteCreateBulk is the builder for creating many BidWebSite entities in bulk.
type BidWebSiteCreateBulk struct {
	config
	err      error
	builders []*BidWebSiteCreate
}

// Save creates the BidWebSite entities in the database.
func (_c *BidWebSiteCreateBulk) Save(ctx context.Context) ([]*BidWebSite, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BidWebSite, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BidWebSiteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BidWebSiteCreateBulk) SaveX(ctx context.Context) []*BidWebSite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BidWebSiteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BidWebSiteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
