// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cds/bid/ent/bidwebsite"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 网站信息
type BidWebSite struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// 省份
	Province string `json:"province,omitempty"`
	// 地市
	City *string `json:"city,omitempty"`
	// 网站名称
	Name string `json:"name,omitempty"`
	// 网站地址
	URL string `json:"url,omitempty"`
	// 是否启用
	Active bool `json:"active,omitempty"`
	// 备注
	Remark string `json:"remark,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 创建人
	CreatedBy *string `json:"created_by,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 更新人
	UpdatedBy *string `json:"updated_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BidWebSiteQuery when eager-loading is set.
	Edges        BidWebSiteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BidWebSiteEdges holds the relations/edges for other nodes in the graph.
type BidWebSiteEdges struct {
	// MemberAccounts holds the value of the member_accounts edge.
	MemberAccounts []*BidMemberAccount `json:"member_accounts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MemberAccountsOrErr returns the MemberAccounts value or an error if the edge
// was not loaded in eager-loading.
func (e BidWebSiteEdges) MemberAccountsOrErr() ([]*BidMemberAccount, error) {
	if e.loadedTypes[0] {
		return e.MemberAccounts, nil
	}
	return nil, &NotLoadedError{edge: "member_accounts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BidWebSite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bidwebsite.FieldActive:
			values[i] = new(sql.NullBool)
		case bidwebsite.FieldID, bidwebsite.FieldProvince, bidwebsite.FieldCity, bidwebsite.FieldName, bidwebsite.FieldURL, bidwebsite.FieldRemark, bidwebsite.FieldCreatedBy, bidwebsite.FieldUpdatedBy:
			values[i] = new(sql.NullString)
		case bidwebsite.FieldCreatedAt, bidwebsite.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BidWebSite fields.
func (_m *BidWebSite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bidwebsite.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case bidwebsite.FieldProvince:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field province", values[i])
			} else if value.Valid {
				_m.Province = value.String
			}
		case bidwebsite.FieldCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field city", values[i])
			} else if value.Valid {
				_m.City = new(string)
				*_m.City = value.String
			}
		case bidwebsite.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case bidwebsite.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case bidwebsite.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case bidwebsite.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		case bidwebsite.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case bidwebsite.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(string)
				*_m.CreatedBy = value.String
			}
		case bidwebsite.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case bidwebsite.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(string)
				*_m.UpdatedBy = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BidWebSite.
// This includes values selected through modifiers, order, etc.
func (_m *BidWebSite) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMemberAccounts queries the "member_accounts" edge of the BidWebSite entity.
func (_m *BidWebSite) QueryMemberAccounts() *BidMemberAccountQuery {
	return NewBidWebSiteClient(_m.config).QueryMemberAccounts(_m)
}

// Update returns a builder for updating this BidWebSite.
// Note that you need to call BidWebSite.Unwrap() before calling this method if this BidWebSite
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BidWebSite) Update() *BidWebSiteUpdateOne {
	return NewBidWebSiteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BidWebSite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BidWebSite) Unwrap() *BidWebSite {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BidWebSite is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BidWebSite) String() string {
	var builder strings.Builder
	builder.WriteString("BidWebSite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("province=")
	builder.WriteString(_m.Province)
	builder.WriteString(", ")
	if v := _m.City; v != nil {
		builder.WriteString("city=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// BidWebSites is a parsable slice of BidWebSite.
type BidWebSites []*BidWebSite
