// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cds/bid/ent/bidapply"
	"cds/bid/ent/bidexpense"
	"cds/bid/ent/bidinfo"
	"cds/bid/ent/bidproject"
	"cds/bid/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bidapplyMixin := schema.BidApply{}.Mixin()
	bidapplyMixinFields0 := bidapplyMixin[0].Fields()
	_ = bidapplyMixinFields0
	bidapplyFields := schema.BidApply{}.Fields()
	_ = bidapplyFields
	// bidapplyDescBusinessID is the schema descriptor for business_id field.
	bidapplyDescBusinessID := bidapplyFields[1].Descriptor()
	// bidapply.BusinessIDValidator is a validator for the "business_id" field. It is called by the builders before save.
	bidapply.BusinessIDValidator = bidapplyDescBusinessID.Validators[0].(func(string) error)
	// bidapplyDescInstanceID is the schema descriptor for instance_id field.
	bidapplyDescInstanceID := bidapplyFields[2].Descriptor()
	// bidapply.InstanceIDValidator is a validator for the "instance_id" field. It is called by the builders before save.
	bidapply.InstanceIDValidator = bidapplyDescInstanceID.Validators[0].(func(string) error)
	// bidapplyDescProjectID is the schema descriptor for project_id field.
	bidapplyDescProjectID := bidapplyFields[3].Descriptor()
	// bidapply.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	bidapply.ProjectIDValidator = bidapplyDescProjectID.Validators[0].(func(string) error)
	// bidapplyDescPurchaserName is the schema descriptor for purchaser_name field.
	bidapplyDescPurchaserName := bidapplyFields[4].Descriptor()
	// bidapply.PurchaserNameValidator is a validator for the "purchaser_name" field. It is called by the builders before save.
	bidapply.PurchaserNameValidator = bidapplyDescPurchaserName.Validators[0].(func(string) error)
	// bidapplyDescAgencyName is the schema descriptor for agency_name field.
	bidapplyDescAgencyName := bidapplyFields[6].Descriptor()
	// bidapply.AgencyNameValidator is a validator for the "agency_name" field. It is called by the builders before save.
	bidapply.AgencyNameValidator = bidapplyDescAgencyName.Validators[0].(func(string) error)
	// bidapplyDescAgencyContact is the schema descriptor for agency_contact field.
	bidapplyDescAgencyContact := bidapplyFields[7].Descriptor()
	// bidapply.AgencyContactValidator is a validator for the "agency_contact" field. It is called by the builders before save.
	bidapply.AgencyContactValidator = bidapplyDescAgencyContact.Validators[0].(func(string) error)
	// bidapplyDescBudgetAmount is the schema descriptor for budget_amount field.
	bidapplyDescBudgetAmount := bidapplyFields[10].Descriptor()
	// bidapply.DefaultBudgetAmount holds the default value on creation for the budget_amount field.
	bidapply.DefaultBudgetAmount = bidapplyDescBudgetAmount.Default.(float64)
	// bidapplyDescDone is the schema descriptor for done field.
	bidapplyDescDone := bidapplyFields[14].Descriptor()
	// bidapply.DefaultDone holds the default value on creation for the done field.
	bidapply.DefaultDone = bidapplyDescDone.Default.(bool)
	// bidapplyDescCreatedAt is the schema descriptor for created_at field.
	bidapplyDescCreatedAt := bidapplyMixinFields0[0].Descriptor()
	// bidapply.DefaultCreatedAt holds the default value on creation for the created_at field.
	bidapply.DefaultCreatedAt = bidapplyDescCreatedAt.Default.(func() time.Time)
	// bidapplyDescCreatedBy is the schema descriptor for created_by field.
	bidapplyDescCreatedBy := bidapplyMixinFields0[1].Descriptor()
	// bidapply.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	bidapply.CreatedByValidator = bidapplyDescCreatedBy.Validators[0].(func(string) error)
	// bidapplyDescUpdatedAt is the schema descriptor for updated_at field.
	bidapplyDescUpdatedAt := bidapplyMixinFields0[2].Descriptor()
	// bidapply.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bidapply.DefaultUpdatedAt = bidapplyDescUpdatedAt.Default.(func() time.Time)
	// bidapply.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bidapply.UpdateDefaultUpdatedAt = bidapplyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bidapplyDescUpdatedBy is the schema descriptor for updated_by field.
	bidapplyDescUpdatedBy := bidapplyMixinFields0[3].Descriptor()
	// bidapply.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	bidapply.UpdatedByValidator = bidapplyDescUpdatedBy.Validators[0].(func(string) error)
	// bidapplyDescID is the schema descriptor for id field.
	bidapplyDescID := bidapplyFields[0].Descriptor()
	// bidapply.IDValidator is a validator for the "id" field. It is called by the builders before save.
	bidapply.IDValidator = bidapplyDescID.Validators[0].(func(string) error)
	bidexpenseMixin := schema.BidExpense{}.Mixin()
	bidexpenseMixinFields0 := bidexpenseMixin[0].Fields()
	_ = bidexpenseMixinFields0
	bidexpenseFields := schema.BidExpense{}.Fields()
	_ = bidexpenseFields
	// bidexpenseDescBusinessID is the schema descriptor for business_id field.
	bidexpenseDescBusinessID := bidexpenseFields[1].Descriptor()
	// bidexpense.BusinessIDValidator is a validator for the "business_id" field. It is called by the builders before save.
	bidexpense.BusinessIDValidator = bidexpenseDescBusinessID.Validators[0].(func(string) error)
	// bidexpenseDescInstanceID is the schema descriptor for instance_id field.
	bidexpenseDescInstanceID := bidexpenseFields[2].Descriptor()
	// bidexpense.InstanceIDValidator is a validator for the "instance_id" field. It is called by the builders before save.
	bidexpense.InstanceIDValidator = bidexpenseDescInstanceID.Validators[0].(func(string) error)
	// bidexpenseDescBillNo is the schema descriptor for bill_no field.
	bidexpenseDescBillNo := bidexpenseFields[3].Descriptor()
	// bidexpense.BillNoValidator is a validator for the "bill_no" field. It is called by the builders before save.
	bidexpense.BillNoValidator = bidexpenseDescBillNo.Validators[0].(func(string) error)
	// bidexpenseDescProjectID is the schema descriptor for project_id field.
	bidexpenseDescProjectID := bidexpenseFields[4].Descriptor()
	// bidexpense.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	bidexpense.ProjectIDValidator = bidexpenseDescProjectID.Validators[0].(func(string) error)
	// bidexpenseDescProjectName is the schema descriptor for project_name field.
	bidexpenseDescProjectName := bidexpenseFields[5].Descriptor()
	// bidexpense.ProjectNameValidator is a validator for the "project_name" field. It is called by the builders before save.
	bidexpense.ProjectNameValidator = bidexpenseDescProjectName.Validators[0].(func(string) error)
	// bidexpenseDescProjectCode is the schema descriptor for project_code field.
	bidexpenseDescProjectCode := bidexpenseFields[6].Descriptor()
	// bidexpense.ProjectCodeValidator is a validator for the "project_code" field. It is called by the builders before save.
	bidexpense.ProjectCodeValidator = bidexpenseDescProjectCode.Validators[0].(func(string) error)
	// bidexpenseDescBizRepName is the schema descriptor for biz_rep_name field.
	bidexpenseDescBizRepName := bidexpenseFields[7].Descriptor()
	// bidexpense.BizRepNameValidator is a validator for the "biz_rep_name" field. It is called by the builders before save.
	bidexpense.BizRepNameValidator = bidexpenseDescBizRepName.Validators[0].(func(string) error)
	// bidexpenseDescPurchaser is the schema descriptor for purchaser field.
	bidexpenseDescPurchaser := bidexpenseFields[8].Descriptor()
	// bidexpense.PurchaserValidator is a validator for the "purchaser" field. It is called by the builders before save.
	bidexpense.PurchaserValidator = bidexpenseDescPurchaser.Validators[0].(func(string) error)
	// bidexpenseDescPayReason is the schema descriptor for pay_reason field.
	bidexpenseDescPayReason := bidexpenseFields[11].Descriptor()
	// bidexpense.PayReasonValidator is a validator for the "pay_reason" field. It is called by the builders before save.
	bidexpense.PayReasonValidator = bidexpenseDescPayReason.Validators[0].(func(string) error)
	// bidexpenseDescRefunded is the schema descriptor for refunded field.
	bidexpenseDescRefunded := bidexpenseFields[12].Descriptor()
	// bidexpense.DefaultRefunded holds the default value on creation for the refunded field.
	bidexpense.DefaultRefunded = bidexpenseDescRefunded.Default.(bool)
	// bidexpenseDescPayeeBank is the schema descriptor for payee_bank field.
	bidexpenseDescPayeeBank := bidexpenseFields[13].Descriptor()
	// bidexpense.PayeeBankValidator is a validator for the "payee_bank" field. It is called by the builders before save.
	bidexpense.PayeeBankValidator = bidexpenseDescPayeeBank.Validators[0].(func(string) error)
	// bidexpenseDescPayeeName is the schema descriptor for payee_name field.
	bidexpenseDescPayeeName := bidexpenseFields[14].Descriptor()
	// bidexpense.PayeeNameValidator is a validator for the "payee_name" field. It is called by the builders before save.
	bidexpense.PayeeNameValidator = bidexpenseDescPayeeName.Validators[0].(func(string) error)
	// bidexpenseDescPayeeAccount is the schema descriptor for payee_account field.
	bidexpenseDescPayeeAccount := bidexpenseFields[15].Descriptor()
	// bidexpense.PayeeAccountValidator is a validator for the "payee_account" field. It is called by the builders before save.
	bidexpense.PayeeAccountValidator = bidexpenseDescPayeeAccount.Validators[0].(func(string) error)
	// bidexpenseDescPayRatio is the schema descriptor for pay_ratio field.
	bidexpenseDescPayRatio := bidexpenseFields[16].Descriptor()
	// bidexpense.DefaultPayRatio holds the default value on creation for the pay_ratio field.
	bidexpense.DefaultPayRatio = bidexpenseDescPayRatio.Default.(float64)
	// bidexpenseDescPayAmount is the schema descriptor for pay_amount field.
	bidexpenseDescPayAmount := bidexpenseFields[17].Descriptor()
	// bidexpense.DefaultPayAmount holds the default value on creation for the pay_amount field.
	bidexpense.DefaultPayAmount = bidexpenseDescPayAmount.Default.(float64)
	// bidexpenseDescPayMethod is the schema descriptor for pay_method field.
	bidexpenseDescPayMethod := bidexpenseFields[19].Descriptor()
	// bidexpense.PayMethodValidator is a validator for the "pay_method" field. It is called by the builders before save.
	bidexpense.PayMethodValidator = bidexpenseDescPayMethod.Validators[0].(func(string) error)
	// bidexpenseDescTransferInstructions is the schema descriptor for transfer_instructions field.
	bidexpenseDescTransferInstructions := bidexpenseFields[20].Descriptor()
	// bidexpense.TransferInstructionsValidator is a validator for the "transfer_instructions" field. It is called by the builders before save.
	bidexpense.TransferInstructionsValidator = bidexpenseDescTransferInstructions.Validators[0].(func(string) error)
	// bidexpenseDescDone is the schema descriptor for done field.
	bidexpenseDescDone := bidexpenseFields[24].Descriptor()
	// bidexpense.DefaultDone holds the default value on creation for the done field.
	bidexpense.DefaultDone = bidexpenseDescDone.Default.(bool)
	// bidexpenseDescCreatedAt is the schema descriptor for created_at field.
	bidexpenseDescCreatedAt := bidexpenseMixinFields0[0].Descriptor()
	// bidexpense.DefaultCreatedAt holds the default value on creation for the created_at field.
	bidexpense.DefaultCreatedAt = bidexpenseDescCreatedAt.Default.(func() time.Time)
	// bidexpenseDescCreatedBy is the schema descriptor for created_by field.
	bidexpenseDescCreatedBy := bidexpenseMixinFields0[1].Descriptor()
	// bidexpense.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	bidexpense.CreatedByValidator = bidexpenseDescCreatedBy.Validators[0].(func(string) error)
	// bidexpenseDescUpdatedAt is the schema descriptor for updated_at field.
	bidexpenseDescUpdatedAt := bidexpenseMixinFields0[2].Descriptor()
	// bidexpense.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bidexpense.DefaultUpdatedAt = bidexpenseDescUpdatedAt.Default.(func() time.Time)
	// bidexpense.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bidexpense.UpdateDefaultUpdatedAt = bidexpenseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bidexpenseDescUpdatedBy is the schema descriptor for updated_by field.
	bidexpenseDescUpdatedBy := bidexpenseMixinFields0[3].Descriptor()
	// bidexpense.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	bidexpense.UpdatedByValidator = bidexpenseDescUpdatedBy.Validators[0].(func(string) error)
	// bidexpenseDescID is the schema descriptor for id field.
	bidexpenseDescID := bidexpenseFields[0].Descriptor()
	// bidexpense.IDValidator is a validator for the "id" field. It is called by the builders before save.
	bidexpense.IDValidator = bidexpenseDescID.Validators[0].(func(string) error)
	bidinfoMixin := schema.BidInfo{}.Mixin()
	bidinfoMixinFields0 := bidinfoMixin[0].Fields()
	_ = bidinfoMixinFields0
	bidinfoFields := schema.BidInfo{}.Fields()
	_ = bidinfoFields
	// bidinfoDescProjectID is the schema descriptor for project_id field.
	bidinfoDescProjectID := bidinfoFields[1].Descriptor()
	// bidinfo.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	bidinfo.ProjectIDValidator = bidinfoDescProjectID.Validators[0].(func(string) error)
	// bidinfoDescGroupLeader is the schema descriptor for group_leader field.
	bidinfoDescGroupLeader := bidinfoFields[2].Descriptor()
	// bidinfo.GroupLeaderValidator is a validator for the "group_leader" field. It is called by the builders before save.
	bidinfo.GroupLeaderValidator = bidinfoDescGroupLeader.Validators[0].(func(string) error)
	// bidinfoDescGroupLeaderName is the schema descriptor for group_leader_name field.
	bidinfoDescGroupLeaderName := bidinfoFields[3].Descriptor()
	// bidinfo.GroupLeaderNameValidator is a validator for the "group_leader_name" field. It is called by the builders before save.
	bidinfo.GroupLeaderNameValidator = bidinfoDescGroupLeaderName.Validators[0].(func(string) error)
	// bidinfoDescBidSubjectCode is the schema descriptor for bid_subject_code field.
	bidinfoDescBidSubjectCode := bidinfoFields[4].Descriptor()
	// bidinfo.BidSubjectCodeValidator is a validator for the "bid_subject_code" field. It is called by the builders before save.
	bidinfo.BidSubjectCodeValidator = bidinfoDescBidSubjectCode.Validators[0].(func(string) error)
	// bidinfoDescBidSubjectName is the schema descriptor for bid_subject_name field.
	bidinfoDescBidSubjectName := bidinfoFields[5].Descriptor()
	// bidinfo.BidSubjectNameValidator is a validator for the "bid_subject_name" field. It is called by the builders before save.
	bidinfo.BidSubjectNameValidator = bidinfoDescBidSubjectName.Validators[0].(func(string) error)
	// bidinfoDescBidAmount is the schema descriptor for bid_amount field.
	bidinfoDescBidAmount := bidinfoFields[6].Descriptor()
	// bidinfo.DefaultBidAmount holds the default value on creation for the bid_amount field.
	bidinfo.DefaultBidAmount = bidinfoDescBidAmount.Default.(float64)
	// bidinfoDescSoftwareAmount is the schema descriptor for software_amount field.
	bidinfoDescSoftwareAmount := bidinfoFields[9].Descriptor()
	// bidinfo.DefaultSoftwareAmount holds the default value on creation for the software_amount field.
	bidinfo.DefaultSoftwareAmount = bidinfoDescSoftwareAmount.Default.(float64)
	// bidinfoDescHardwareAmount is the schema descriptor for hardware_amount field.
	bidinfoDescHardwareAmount := bidinfoFields[10].Descriptor()
	// bidinfo.DefaultHardwareAmount holds the default value on creation for the hardware_amount field.
	bidinfo.DefaultHardwareAmount = bidinfoDescHardwareAmount.Default.(float64)
	// bidinfoDescOperationAmount is the schema descriptor for operation_amount field.
	bidinfoDescOperationAmount := bidinfoFields[11].Descriptor()
	// bidinfo.DefaultOperationAmount holds the default value on creation for the operation_amount field.
	bidinfo.DefaultOperationAmount = bidinfoDescOperationAmount.Default.(float64)
	// bidinfoDescContractSigned is the schema descriptor for contract_signed field.
	bidinfoDescContractSigned := bidinfoFields[13].Descriptor()
	// bidinfo.DefaultContractSigned holds the default value on creation for the contract_signed field.
	bidinfo.DefaultContractSigned = bidinfoDescContractSigned.Default.(bool)
	// bidinfoDescContractNo is the schema descriptor for contract_no field.
	bidinfoDescContractNo := bidinfoFields[14].Descriptor()
	// bidinfo.ContractNoValidator is a validator for the "contract_no" field. It is called by the builders before save.
	bidinfo.ContractNoValidator = bidinfoDescContractNo.Validators[0].(func(string) error)
	// bidinfoDescCreatedAt is the schema descriptor for created_at field.
	bidinfoDescCreatedAt := bidinfoMixinFields0[0].Descriptor()
	// bidinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	bidinfo.DefaultCreatedAt = bidinfoDescCreatedAt.Default.(func() time.Time)
	// bidinfoDescCreatedBy is the schema descriptor for created_by field.
	bidinfoDescCreatedBy := bidinfoMixinFields0[1].Descriptor()
	// bidinfo.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	bidinfo.CreatedByValidator = bidinfoDescCreatedBy.Validators[0].(func(string) error)
	// bidinfoDescUpdatedAt is the schema descriptor for updated_at field.
	bidinfoDescUpdatedAt := bidinfoMixinFields0[2].Descriptor()
	// bidinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bidinfo.DefaultUpdatedAt = bidinfoDescUpdatedAt.Default.(func() time.Time)
	// bidinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bidinfo.UpdateDefaultUpdatedAt = bidinfoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bidinfoDescUpdatedBy is the schema descriptor for updated_by field.
	bidinfoDescUpdatedBy := bidinfoMixinFields0[3].Descriptor()
	// bidinfo.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	bidinfo.UpdatedByValidator = bidinfoDescUpdatedBy.Validators[0].(func(string) error)
	// bidinfoDescID is the schema descriptor for id field.
	bidinfoDescID := bidinfoFields[0].Descriptor()
	// bidinfo.IDValidator is a validator for the "id" field. It is called by the builders before save.
	bidinfo.IDValidator = bidinfoDescID.Validators[0].(func(string) error)
	bidprojectMixin := schema.BidProject{}.Mixin()
	bidprojectMixinFields0 := bidprojectMixin[0].Fields()
	_ = bidprojectMixinFields0
	bidprojectFields := schema.BidProject{}.Fields()
	_ = bidprojectFields
	// bidprojectDescCode is the schema descriptor for code field.
	bidprojectDescCode := bidprojectFields[1].Descriptor()
	// bidproject.DefaultCode holds the default value on creation for the code field.
	bidproject.DefaultCode = bidprojectDescCode.Default.(string)
	// bidproject.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	bidproject.CodeValidator = bidprojectDescCode.Validators[0].(func(string) error)
	// bidprojectDescName is the schema descriptor for name field.
	bidprojectDescName := bidprojectFields[2].Descriptor()
	// bidproject.NameValidator is a validator for the "name" field. It is called by the builders before save.
	bidproject.NameValidator = bidprojectDescName.Validators[0].(func(string) error)
	// bidprojectDescDepartmentCode is the schema descriptor for department_code field.
	bidprojectDescDepartmentCode := bidprojectFields[4].Descriptor()
	// bidproject.DefaultDepartmentCode holds the default value on creation for the department_code field.
	bidproject.DefaultDepartmentCode = bidprojectDescDepartmentCode.Default.(string)
	// bidproject.DepartmentCodeValidator is a validator for the "department_code" field. It is called by the builders before save.
	bidproject.DepartmentCodeValidator = bidprojectDescDepartmentCode.Validators[0].(func(string) error)
	// bidprojectDescDepartmentName is the schema descriptor for department_name field.
	bidprojectDescDepartmentName := bidprojectFields[5].Descriptor()
	// bidproject.DepartmentNameValidator is a validator for the "department_name" field. It is called by the builders before save.
	bidproject.DepartmentNameValidator = bidprojectDescDepartmentName.Validators[0].(func(string) error)
	// bidprojectDescBizRepNo is the schema descriptor for biz_rep_no field.
	bidprojectDescBizRepNo := bidprojectFields[6].Descriptor()
	// bidproject.DefaultBizRepNo holds the default value on creation for the biz_rep_no field.
	bidproject.DefaultBizRepNo = bidprojectDescBizRepNo.Default.(string)
	// bidproject.BizRepNoValidator is a validator for the "biz_rep_no" field. It is called by the builders before save.
	bidproject.BizRepNoValidator = bidprojectDescBizRepNo.Validators[0].(func(string) error)
	// bidprojectDescBizRepName is the schema descriptor for biz_rep_name field.
	bidprojectDescBizRepName := bidprojectFields[7].Descriptor()
	// bidproject.DefaultBizRepName holds the default value on creation for the biz_rep_name field.
	bidproject.DefaultBizRepName = bidprojectDescBizRepName.Default.(string)
	// bidproject.BizRepNameValidator is a validator for the "biz_rep_name" field. It is called by the builders before save.
	bidproject.BizRepNameValidator = bidprojectDescBizRepName.Validators[0].(func(string) error)
	// bidprojectDescSourceID is the schema descriptor for source_id field.
	bidprojectDescSourceID := bidprojectFields[9].Descriptor()
	// bidproject.SourceIDValidator is a validator for the "source_id" field. It is called by the builders before save.
	bidproject.SourceIDValidator = bidprojectDescSourceID.Validators[0].(func(string) error)
	// bidprojectDescCreatedAt is the schema descriptor for created_at field.
	bidprojectDescCreatedAt := bidprojectMixinFields0[0].Descriptor()
	// bidproject.DefaultCreatedAt holds the default value on creation for the created_at field.
	bidproject.DefaultCreatedAt = bidprojectDescCreatedAt.Default.(func() time.Time)
	// bidprojectDescCreatedBy is the schema descriptor for created_by field.
	bidprojectDescCreatedBy := bidprojectMixinFields0[1].Descriptor()
	// bidproject.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	bidproject.CreatedByValidator = bidprojectDescCreatedBy.Validators[0].(func(string) error)
	// bidprojectDescUpdatedAt is the schema descriptor for updated_at field.
	bidprojectDescUpdatedAt := bidprojectMixinFields0[2].Descriptor()
	// bidproject.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bidproject.DefaultUpdatedAt = bidprojectDescUpdatedAt.Default.(func() time.Time)
	// bidproject.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bidproject.UpdateDefaultUpdatedAt = bidprojectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bidprojectDescUpdatedBy is the schema descriptor for updated_by field.
	bidprojectDescUpdatedBy := bidprojectMixinFields0[3].Descriptor()
	// bidproject.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	bidproject.UpdatedByValidator = bidprojectDescUpdatedBy.Validators[0].(func(string) error)
	// bidprojectDescID is the schema descriptor for id field.
	bidprojectDescID := bidprojectFields[0].Descriptor()
	// bidproject.IDValidator is a validator for the "id" field. It is called by the builders before save.
	bidproject.IDValidator = bidprojectDescID.Validators[0].(func(string) error)
}
