// Code generated by ent, DO NOT EDIT.

package bidcacertificate

import (
	"cds/bid/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContainsFold(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldName, v))
}

// ExpiryTime applies equality check predicate on the "expiry_time" field. It's identical to ExpiryTimeEQ.
func ExpiryTime(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldExpiryTime, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldPassword, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldRemark, v))
}

// LastRenewalAt applies equality check predicate on the "last_renewal_at" field. It's identical to LastRenewalAtEQ.
func LastRenewalAt(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldLastRenewalAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldUpdatedBy, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContainsFold(FieldName, v))
}

// ExpiryTimeEQ applies the EQ predicate on the "expiry_time" field.
func ExpiryTimeEQ(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldExpiryTime, v))
}

// ExpiryTimeNEQ applies the NEQ predicate on the "expiry_time" field.
func ExpiryTimeNEQ(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldExpiryTime, v))
}

// ExpiryTimeIn applies the In predicate on the "expiry_time" field.
func ExpiryTimeIn(vs ...time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldExpiryTime, vs...))
}

// ExpiryTimeNotIn applies the NotIn predicate on the "expiry_time" field.
func ExpiryTimeNotIn(vs ...time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldExpiryTime, vs...))
}

// ExpiryTimeGT applies the GT predicate on the "expiry_time" field.
func ExpiryTimeGT(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldExpiryTime, v))
}

// ExpiryTimeGTE applies the GTE predicate on the "expiry_time" field.
func ExpiryTimeGTE(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldExpiryTime, v))
}

// ExpiryTimeLT applies the LT predicate on the "expiry_time" field.
func ExpiryTimeLT(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldExpiryTime, v))
}

// ExpiryTimeLTE applies the LTE predicate on the "expiry_time" field.
func ExpiryTimeLTE(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldExpiryTime, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContainsFold(FieldPassword, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContainsFold(FieldRemark, v))
}

// LastRenewalAtEQ applies the EQ predicate on the "last_renewal_at" field.
func LastRenewalAtEQ(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldLastRenewalAt, v))
}

// LastRenewalAtNEQ applies the NEQ predicate on the "last_renewal_at" field.
func LastRenewalAtNEQ(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldLastRenewalAt, v))
}

// LastRenewalAtIn applies the In predicate on the "last_renewal_at" field.
func LastRenewalAtIn(vs ...time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldLastRenewalAt, vs...))
}

// LastRenewalAtNotIn applies the NotIn predicate on the "last_renewal_at" field.
func LastRenewalAtNotIn(vs ...time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldLastRenewalAt, vs...))
}

// LastRenewalAtGT applies the GT predicate on the "last_renewal_at" field.
func LastRenewalAtGT(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldLastRenewalAt, v))
}

// LastRenewalAtGTE applies the GTE predicate on the "last_renewal_at" field.
func LastRenewalAtGTE(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldLastRenewalAt, v))
}

// LastRenewalAtLT applies the LT predicate on the "last_renewal_at" field.
func LastRenewalAtLT(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldLastRenewalAt, v))
}

// LastRenewalAtLTE applies the LTE predicate on the "last_renewal_at" field.
func LastRenewalAtLTE(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldLastRenewalAt, v))
}

// LastRenewalAtIsNil applies the IsNil predicate on the "last_renewal_at" field.
func LastRenewalAtIsNil() predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIsNull(FieldLastRenewalAt))
}

// LastRenewalAtNotNil applies the NotNil predicate on the "last_renewal_at" field.
func LastRenewalAtNotNil() predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotNull(FieldLastRenewalAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// HasAccountRelations applies the HasEdge predicate on the "account_relations" edge.
func HasAccountRelations() predicate.BidCACertificate {
	return predicate.BidCACertificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountRelationsTable, AccountRelationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountRelationsWith applies the HasEdge predicate on the "account_relations" edge with a given conditions (other predicates).
func HasAccountRelationsWith(preds ...predicate.BidAccountRelation) predicate.BidCACertificate {
	return predicate.BidCACertificate(func(s *sql.Selector) {
		step := newAccountRelationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BidCACertificate) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BidCACertificate) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BidCACertificate) predicate.BidCACertificate {
	return predicate.BidCACertificate(sql.NotPredicates(p))
}
