-- Create "bid_project" table
CREATE TABLE `bid_project` (
  `id` varchar(32) NOT NULL COMMENT "项目 ID",
  `code` varchar(64) NOT NULL DEFAULT "" COMMENT "项目编码",
  `name` varchar(64) NOT NULL COMMENT "项目名称",
  `type` enum('S','H','I','OM','UP') NOT NULL DEFAULT "UP" COMMENT "项目类型 S:软件 H:硬件 I:软硬件集成 OM:运维服务 UP:其他",
  `department_code` varchar(64) NOT NULL DEFAULT "" COMMENT "所属部门编码",
  `department_name` varchar(64) NOT NULL COMMENT "所属部门名称",
  `biz_rep_no` varchar(8) NOT NULL DEFAULT "" COMMENT "商务代表工号",
  `biz_rep_name` varchar(16) NOT NULL DEFAULT "" COMMENT "商务代表",
  `source` enum('BA','SC','0') NOT NULL DEFAULT "0" COMMENT "项目来源",
  `source_id` varchar(64) NULL COMMENT "来源标识 SC:销售合同号",
  `created_at` datetime(3) NOT NULL COMMENT "创建时间",
  `created_by` varchar(32) NULL COMMENT "创建人",
  `updated_at` datetime(3) NOT NULL COMMENT "更新时间",
  `updated_by` varchar(32) NULL COMMENT "更新人",
  `remark` longtext NULL COMMENT "备注信息",
  PRIMARY KEY (`id`),
  INDEX `idx_code_name` (`code`, `name`),
  INDEX `idx_department_code` (`department_code`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin COMMENT "投标项目";
-- Create "bid_apply" table
CREATE TABLE `bid_apply` (
  `id` varchar(32) NOT NULL COMMENT "投标申请 ID",
  `business_id` varchar(32) NOT NULL COMMENT "审批编号",
  `instance_id` varchar(64) NOT NULL COMMENT "审批实例 ID",
  `purchaser_name` varchar(64) NULL COMMENT "采购人名称",
  `bid_type` enum('UT','OT','IT','CN','IP','SSP','CC','SCT','CIP','HIP','PC','DP') NOT NULL DEFAULT "UT" COMMENT "招标类型 UT:未知类型 OT:公开招标 IT:邀请招标 CN:竞争性谈判 IP:询价采购 SSP:单一来源采购 CC:竞争性磋商 SCT:自行招标 CIP:询比采购 HIP:医院自主采购 PC:比价 DP:直接采购",
  `agency_name` varchar(64) NULL COMMENT "招标代理机构名称",
  `agency_contact` varchar(128) NULL COMMENT "招标代理机构联系人及电话",
  `opening_date` datetime NULL COMMENT "开标时间",
  `notice_url` longtext NULL COMMENT "招标公告网址",
  `budget_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT "预算金额（元）",
  `remark` longtext NULL COMMENT "备注说明;如资质要求、技术难点、事项说明等",
  `attachments` json NULL COMMENT "投标报名相关附件",
  `approval_status` varchar(255) NOT NULL COMMENT "审批状态",
  `done` bool NOT NULL DEFAULT 0 COMMENT "审批流程是否已结束",
  `created_at` datetime(3) NOT NULL COMMENT "创建时间",
  `created_by` varchar(32) NULL COMMENT "创建人",
  `updated_at` datetime(3) NOT NULL COMMENT "更新时间",
  `updated_by` varchar(32) NULL COMMENT "更新人",
  `project_id` varchar(32) NOT NULL COMMENT "项目 ID",
  PRIMARY KEY (`id`),
  INDEX `idx_approval_status` (`approval_status`),
  UNIQUE INDEX `project_id` (`project_id`),
  CONSTRAINT `fk_pid_01` FOREIGN KEY (`project_id`) REFERENCES `bid_project` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE
) CHARSET utf8mb4 COLLATE utf8mb4_bin COMMENT "投标申请";
-- Create "bid_expense" table
CREATE TABLE `bid_expense` (
  `id` varchar(32) NOT NULL COMMENT "投标支出 ID",
  `business_id` varchar(32) NOT NULL COMMENT "审批编号",
  `instance_id` varchar(64) NOT NULL COMMENT "审批实例 ID",
  `bill_no` varchar(16) NOT NULL COMMENT "单据编码",
  `project_name` varchar(64) NOT NULL COMMENT "项目名称",
  `project_code` varchar(64) NOT NULL COMMENT "项目编码",
  `biz_rep_name` varchar(16) NOT NULL COMMENT "商务代表",
  `purchaser` varchar(64) NULL COMMENT "采购人名称",
  `fee_type_v1` varchar(255) NULL COMMENT "费用类型",
  `fee_type` enum('RF','DF','CA','EF','BB','BS','PB','PG','OE','EB') NOT NULL DEFAULT "OE" COMMENT "费用类型 RF:报名费 DF:标书工本费 CA:CA费用 EF:专家费 BB:投标保证金 BS:中标服务费 PB:履约保证金 PG:预付保函 OE:其他费用 EB:入库保证金",
  `pay_reason` varchar(64) NULL COMMENT "付款事由",
  `refunded` bool NOT NULL DEFAULT 0 COMMENT "是否（保证金）退还金额",
  `payee_bank` varchar(64) NOT NULL COMMENT "收款方开户银行",
  `payee_name` varchar(64) NOT NULL COMMENT "收款方账户名称",
  `payee_account` varchar(64) NOT NULL COMMENT "收款方账号",
  `pay_ratio` decimal(5,2) NOT NULL DEFAULT 100.00 COMMENT "付款比例",
  `pay_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT "付款金额（元）",
  `pay_remark` longtext NULL COMMENT "付款备注",
  `pay_method` varchar(64) NULL COMMENT "付款方式",
  `transfer_instructions` varchar(128) NULL COMMENT "转账说明",
  `guarantee_deadline` datetime NULL COMMENT "保证期限（保函）",
  `plan_pay_time` datetime NULL COMMENT "预计转账时间",
  `approval_status` varchar(255) NOT NULL COMMENT "费用审批状态",
  `done` bool NOT NULL DEFAULT 0 COMMENT "审批流程是否已结束",
  `created_at` datetime(3) NOT NULL COMMENT "创建时间",
  `created_by` varchar(32) NULL COMMENT "创建人",
  `updated_at` datetime(3) NOT NULL COMMENT "更新时间",
  `updated_by` varchar(32) NULL COMMENT "更新人",
  `project_id` varchar(32) NULL COMMENT "项目 ID",
  PRIMARY KEY (`id`),
  INDEX `fk_pid_02` (`project_id`),
  INDEX `idx_approval_status` (`approval_status`),
  INDEX `idx_bill_no` (`bill_no`),
  INDEX `idx_fee_type` (`fee_type`),
  CONSTRAINT `fk_pid_02` FOREIGN KEY (`project_id`) REFERENCES `bid_project` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE
) CHARSET utf8mb4 COLLATE utf8mb4_bin COMMENT "投标费用支出";
-- Create "bid_info" table
CREATE TABLE `bid_info` (
  `id` varchar(32) NOT NULL COMMENT "投标信息ID",
  `bid_subject_code` varchar(32) NOT NULL COMMENT "投标主体编码",
  `bid_subject_name` varchar(32) NOT NULL COMMENT "投标主体名称",
  `bid_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT "投标金额",
  `bid_status` enum('RP','RO','RS','RF','DP','B','W','L','F','0') NOT NULL DEFAULT "0" COMMENT "投标状态 RP:待报名 RO:报名中 RS:报名成功 RF:报名失败 DP:标书编制中 B:投标中 W:已中标 L:未中标 F:流标 0:-",
  `bid_date` datetime NULL COMMENT "中标时间",
  `software_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT "中标软件金额",
  `hardware_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT "中标硬件金额",
  `operation_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT "中标运维金额",
  `result_url` longtext NULL COMMENT "中标结果网址",
  `contract_signed` bool NOT NULL DEFAULT 0 COMMENT "销售合同是否签署",
  `contract_no` varchar(64) NULL COMMENT "销售合同号",
  `contract_sign_date` datetime NULL COMMENT "销售合同签署日期",
  `remark` longtext NULL COMMENT "备注信息",
  `created_at` datetime(3) NOT NULL COMMENT "创建时间",
  `created_by` varchar(32) NULL COMMENT "创建人",
  `updated_at` datetime(3) NOT NULL COMMENT "更新时间",
  `updated_by` varchar(32) NULL COMMENT "更新人",
  `project_id` varchar(32) NOT NULL COMMENT "项目 ID",
  PRIMARY KEY (`id`),
  INDEX `fk_pid_03` (`project_id`),
  INDEX `idx_bid_status` (`bid_status`),
  CONSTRAINT `fk_pid_03` FOREIGN KEY (`project_id`) REFERENCES `bid_project` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE
) CHARSET utf8mb4 COLLATE utf8mb4_bin COMMENT "投标信息";
