// Code generated by ent, DO NOT EDIT.

package bidproject

import (
	"cds/bid/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldName, v))
}

// DepartmentCode applies equality check predicate on the "department_code" field. It's identical to DepartmentCodeEQ.
func DepartmentCode(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldDepartmentCode, v))
}

// DepartmentName applies equality check predicate on the "department_name" field. It's identical to DepartmentNameEQ.
func DepartmentName(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldDepartmentName, v))
}

// BizRepNo applies equality check predicate on the "biz_rep_no" field. It's identical to BizRepNoEQ.
func BizRepNo(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldBizRepNo, v))
}

// BizRepName applies equality check predicate on the "biz_rep_name" field. It's identical to BizRepNameEQ.
func BizRepName(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldBizRepName, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldSourceID, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldRemark, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldUpdatedBy, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldType, vs...))
}

// DepartmentCodeEQ applies the EQ predicate on the "department_code" field.
func DepartmentCodeEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldDepartmentCode, v))
}

// DepartmentCodeNEQ applies the NEQ predicate on the "department_code" field.
func DepartmentCodeNEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldDepartmentCode, v))
}

// DepartmentCodeIn applies the In predicate on the "department_code" field.
func DepartmentCodeIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldDepartmentCode, vs...))
}

// DepartmentCodeNotIn applies the NotIn predicate on the "department_code" field.
func DepartmentCodeNotIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldDepartmentCode, vs...))
}

// DepartmentCodeGT applies the GT predicate on the "department_code" field.
func DepartmentCodeGT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldDepartmentCode, v))
}

// DepartmentCodeGTE applies the GTE predicate on the "department_code" field.
func DepartmentCodeGTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldDepartmentCode, v))
}

// DepartmentCodeLT applies the LT predicate on the "department_code" field.
func DepartmentCodeLT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldDepartmentCode, v))
}

// DepartmentCodeLTE applies the LTE predicate on the "department_code" field.
func DepartmentCodeLTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldDepartmentCode, v))
}

// DepartmentCodeContains applies the Contains predicate on the "department_code" field.
func DepartmentCodeContains(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContains(FieldDepartmentCode, v))
}

// DepartmentCodeHasPrefix applies the HasPrefix predicate on the "department_code" field.
func DepartmentCodeHasPrefix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasPrefix(FieldDepartmentCode, v))
}

// DepartmentCodeHasSuffix applies the HasSuffix predicate on the "department_code" field.
func DepartmentCodeHasSuffix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasSuffix(FieldDepartmentCode, v))
}

// DepartmentCodeEqualFold applies the EqualFold predicate on the "department_code" field.
func DepartmentCodeEqualFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldDepartmentCode, v))
}

// DepartmentCodeContainsFold applies the ContainsFold predicate on the "department_code" field.
func DepartmentCodeContainsFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldDepartmentCode, v))
}

// DepartmentNameEQ applies the EQ predicate on the "department_name" field.
func DepartmentNameEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldDepartmentName, v))
}

// DepartmentNameNEQ applies the NEQ predicate on the "department_name" field.
func DepartmentNameNEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldDepartmentName, v))
}

// DepartmentNameIn applies the In predicate on the "department_name" field.
func DepartmentNameIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldDepartmentName, vs...))
}

// DepartmentNameNotIn applies the NotIn predicate on the "department_name" field.
func DepartmentNameNotIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldDepartmentName, vs...))
}

// DepartmentNameGT applies the GT predicate on the "department_name" field.
func DepartmentNameGT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldDepartmentName, v))
}

// DepartmentNameGTE applies the GTE predicate on the "department_name" field.
func DepartmentNameGTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldDepartmentName, v))
}

// DepartmentNameLT applies the LT predicate on the "department_name" field.
func DepartmentNameLT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldDepartmentName, v))
}

// DepartmentNameLTE applies the LTE predicate on the "department_name" field.
func DepartmentNameLTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldDepartmentName, v))
}

// DepartmentNameContains applies the Contains predicate on the "department_name" field.
func DepartmentNameContains(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContains(FieldDepartmentName, v))
}

// DepartmentNameHasPrefix applies the HasPrefix predicate on the "department_name" field.
func DepartmentNameHasPrefix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasPrefix(FieldDepartmentName, v))
}

// DepartmentNameHasSuffix applies the HasSuffix predicate on the "department_name" field.
func DepartmentNameHasSuffix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasSuffix(FieldDepartmentName, v))
}

// DepartmentNameEqualFold applies the EqualFold predicate on the "department_name" field.
func DepartmentNameEqualFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldDepartmentName, v))
}

// DepartmentNameContainsFold applies the ContainsFold predicate on the "department_name" field.
func DepartmentNameContainsFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldDepartmentName, v))
}

// BizRepNoEQ applies the EQ predicate on the "biz_rep_no" field.
func BizRepNoEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldBizRepNo, v))
}

// BizRepNoNEQ applies the NEQ predicate on the "biz_rep_no" field.
func BizRepNoNEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldBizRepNo, v))
}

// BizRepNoIn applies the In predicate on the "biz_rep_no" field.
func BizRepNoIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldBizRepNo, vs...))
}

// BizRepNoNotIn applies the NotIn predicate on the "biz_rep_no" field.
func BizRepNoNotIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldBizRepNo, vs...))
}

// BizRepNoGT applies the GT predicate on the "biz_rep_no" field.
func BizRepNoGT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldBizRepNo, v))
}

// BizRepNoGTE applies the GTE predicate on the "biz_rep_no" field.
func BizRepNoGTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldBizRepNo, v))
}

// BizRepNoLT applies the LT predicate on the "biz_rep_no" field.
func BizRepNoLT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldBizRepNo, v))
}

// BizRepNoLTE applies the LTE predicate on the "biz_rep_no" field.
func BizRepNoLTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldBizRepNo, v))
}

// BizRepNoContains applies the Contains predicate on the "biz_rep_no" field.
func BizRepNoContains(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContains(FieldBizRepNo, v))
}

// BizRepNoHasPrefix applies the HasPrefix predicate on the "biz_rep_no" field.
func BizRepNoHasPrefix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasPrefix(FieldBizRepNo, v))
}

// BizRepNoHasSuffix applies the HasSuffix predicate on the "biz_rep_no" field.
func BizRepNoHasSuffix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasSuffix(FieldBizRepNo, v))
}

// BizRepNoEqualFold applies the EqualFold predicate on the "biz_rep_no" field.
func BizRepNoEqualFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldBizRepNo, v))
}

// BizRepNoContainsFold applies the ContainsFold predicate on the "biz_rep_no" field.
func BizRepNoContainsFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldBizRepNo, v))
}

// BizRepNameEQ applies the EQ predicate on the "biz_rep_name" field.
func BizRepNameEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldBizRepName, v))
}

// BizRepNameNEQ applies the NEQ predicate on the "biz_rep_name" field.
func BizRepNameNEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldBizRepName, v))
}

// BizRepNameIn applies the In predicate on the "biz_rep_name" field.
func BizRepNameIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldBizRepName, vs...))
}

// BizRepNameNotIn applies the NotIn predicate on the "biz_rep_name" field.
func BizRepNameNotIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldBizRepName, vs...))
}

// BizRepNameGT applies the GT predicate on the "biz_rep_name" field.
func BizRepNameGT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldBizRepName, v))
}

// BizRepNameGTE applies the GTE predicate on the "biz_rep_name" field.
func BizRepNameGTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldBizRepName, v))
}

// BizRepNameLT applies the LT predicate on the "biz_rep_name" field.
func BizRepNameLT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldBizRepName, v))
}

// BizRepNameLTE applies the LTE predicate on the "biz_rep_name" field.
func BizRepNameLTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldBizRepName, v))
}

// BizRepNameContains applies the Contains predicate on the "biz_rep_name" field.
func BizRepNameContains(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContains(FieldBizRepName, v))
}

// BizRepNameHasPrefix applies the HasPrefix predicate on the "biz_rep_name" field.
func BizRepNameHasPrefix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasPrefix(FieldBizRepName, v))
}

// BizRepNameHasSuffix applies the HasSuffix predicate on the "biz_rep_name" field.
func BizRepNameHasSuffix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasSuffix(FieldBizRepName, v))
}

// BizRepNameEqualFold applies the EqualFold predicate on the "biz_rep_name" field.
func BizRepNameEqualFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldBizRepName, v))
}

// BizRepNameContainsFold applies the ContainsFold predicate on the "biz_rep_name" field.
func BizRepNameContainsFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldBizRepName, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldSource, vs...))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.BidProject {
	return predicate.BidProject(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.BidProject {
	return predicate.BidProject(sql.FieldNotNull(FieldSourceID))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldSourceID, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.BidProject {
	return predicate.BidProject(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.BidProject {
	return predicate.BidProject(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.BidProject {
	return predicate.BidProject(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.BidProject {
	return predicate.BidProject(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.BidProject {
	return predicate.BidProject(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.BidProject {
	return predicate.BidProject(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.BidProject {
	return predicate.BidProject(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.BidProject {
	return predicate.BidProject(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// HasApply applies the HasEdge predicate on the "apply" edge.
func HasApply() predicate.BidProject {
	return predicate.BidProject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ApplyTable, ApplyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplyWith applies the HasEdge predicate on the "apply" edge with a given conditions (other predicates).
func HasApplyWith(preds ...predicate.BidApply) predicate.BidProject {
	return predicate.BidProject(func(s *sql.Selector) {
		step := newApplyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExpense applies the HasEdge predicate on the "expense" edge.
func HasExpense() predicate.BidProject {
	return predicate.BidProject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExpenseTable, ExpenseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExpenseWith applies the HasEdge predicate on the "expense" edge with a given conditions (other predicates).
func HasExpenseWith(preds ...predicate.BidExpense) predicate.BidProject {
	return predicate.BidProject(func(s *sql.Selector) {
		step := newExpenseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInfo applies the HasEdge predicate on the "info" edge.
func HasInfo() predicate.BidProject {
	return predicate.BidProject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, InfoTable, InfoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInfoWith applies the HasEdge predicate on the "info" edge with a given conditions (other predicates).
func HasInfoWith(preds ...predicate.BidInfo) predicate.BidProject {
	return predicate.BidProject(func(s *sql.Selector) {
		step := newInfoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BidProject) predicate.BidProject {
	return predicate.BidProject(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BidProject) predicate.BidProject {
	return predicate.BidProject(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BidProject) predicate.BidProject {
	return predicate.BidProject(sql.NotPredicates(p))
}
